### ISSUE TITLE
Firefox addon requirs manual approval on every website visit

### ISSUE THREAD

**Issue by tmr232** [ActivityWatch/aw-watcher-web#121]
When I go to a new website, or refresh a page, I need to manually enable the addon to have it record anything:

![image](https://github.com/ActivityWatch/aw-watcher-web/assets/1386239/d60bb3c3-af38-4761-aee2-fcf1c3cc6826)

![image](https://github.com/ActivityWatch/aw-watcher-web/assets/1386239/631ef565-ebed-4a76-a319-01c3a265ebe2)

Is there a way to make it run automatically?

**Comment by tomhense** [comment]
I don't think this manual approval is needed, for me websites are listed without problems in the activity watch timeline even if I don't manually approve the website. I think this button is only there because manifest v3 addons need to be granted specific domain permissions. This addon is however still using manifest v2 and only queries tabs data (not changing or reading page content).

However this addon will need to be changed to manifest v3 this year if it still wants to support chrome browsers (manifest v2 will still be supported on firefox) so I don't know if this could be a problem in the future.

**Comment by tmr232** [comment]
Oh, yeah, sorry! I realized it wasn't really an issue and forgot to close the issue!
