### ISSUE TITLE
Point to IP address of server

### ISSUE THREAD

**Issue by THofstee** [ActivityWatch/aw-watcher-web#26]
It would be helpful if I could point the extension to something other than 127.0.0.1 for the server, since I can't have aw-server running on localhost under ChromeOS.

**Comment by ErikBjare** [comment]
This won't be supported anytime soon since connecting to the server from other hosts is not supported for security reasons at the moment. Sorry, closing.

**Comment by johan-bjareholt** [comment]
This won't ever be supported until ChromeOS gives some API to expose if the user is AFK and what window is active, so even if we start supporting authentication in aw-server this probably won't be possible to do anyway.

So unless ChromeOS does something about this, it's impossible to implement.

**Comment by ErikBjare** [comment]
And for a little bit of context, ChromeOS has been discussed here before: https://github.com/ActivityWatch/activitywatch/issues/162

**Comment by THofstee** [comment]
I mean, I'm running it through the crostini Linux VM. I just want to point the web browser extension to that so I can at least track sites be it afk or not.

**Comment by johan-bjareholt** [comment]
Still not possible with Crostini sadly.

While you probably can install aw-watcher-afk and aw-watcher-window within Crostini they will be useless since they run inside a container and does not have permissions to track mouse movement or keyboard presses outside of the container.

Chrome OS is great that it is secure by default, but it's really bad in that it does not allow to add exceptions to the security which makes it a very locked down OS. I really wished that ChromeOS would add support for something like flatpak instead of a Linux VM since it's much more powerful and would allow applications to be sandboxed and secure but still being able to add the ability to add more powerful permissions if needed.

**Comment by marcusquinn** [comment]
Don't know how they do it but TimeCamp definitely works on ChromeOS - although would be happy to switch to ActivityWatch if you figure it out:

https://www.timecamp.com
https://chrome.google.com/webstore/detail/timecamp/ohbkdjmhoegleofcohdjagmcnkimfdaa?hl=en
