### ISSUE TITLE
Reenable ability to log incognito tabs

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-web#35]
In https://github.com/ActivityWatch/aw-watcher-web/pull/18 we removed the ability to watch incognito tabs since Firefox did not have a way to disable an extension in incognito mode specifically. It's also not a complete fix for the privacy risk, as the browser title is still logged by the window watcher.

In Firefox 67, this changes. Firefox will now, just like Chrome, have a setting for which extensions to run in incognito mode.

> *"Change to extensions in Private Windows: Any new extensions you add to the browser won’t work in Private Windows unless you allow this in the settings."*
> https://www.mozilla.org/en-US/firefox/67.0beta/releasenotes/

We should probably wait until Firefox 67 has gained traction, then discuss the way forward.

**Comment by BjoernLudwigPTB** [comment]
I would really appreciate using _aw-watcher-web
_ in all my Firefox sessions because the reason I use the private browsing mode is not preventing me from wanting to log my Browser usage in general. Do you think we are ready for that yet? In that case, could you give some hint on how to tackle that? I would really love to put some effort in this, but have no experience with JavaScript. Can we not just revert 6b7ed08e40e1c3ce6df3381652ffda7a4a7f60bb and leave the rest to the Firefox "Enable in private mode" setting which pops up by default whenever a new Add-on is installed and disabled by default?

**Comment by johan-bjareholt** [comment]
@BjoernLudwigPTB Looks to me like reverting that commit should be enough, feel free to do that, test and then submit a PR!

**Comment by BjoernLudwigPTB** [comment]
> @BjoernLudwigPTB Looks to me like reverting that commit should be enough, feel free to do that, test and then submit a PR!

Great! I am very sorry for asking again, but I am not a JavaScript developer and do not know much about it. I got *nodejs*, *npm*, have the repo forked and cloned, initialized the submodules, everything setup to get it done, but I have no idea on how to test what I have 
done. Could you please give me a hint where to look or what to do?

**Comment by ErikBjare** [comment]
@BjoernLudwigPTB 

1. Create a new branch
2. `git revert 8f76cb0`
3. `make install` to install the npm dependencies and build the repo
4. Load the addon (developer mode) in your browser, check that it works as expected
5. Open a PR!

**Comment by johan-bjareholt** [comment]
This seems to be fixed, closing
