### ISSUE TITLE
Update chrome extension version

### ISSUE THREAD

**Issue by je-l** [ActivityWatch/aw-watcher-web#42]
Chrome web store has version 0.2.3 while Firefox has 0.3.1 available.

Maybe a CI setup with automatic deploys would be useful.

**Comment by ErikBjare** [comment]
Automatically deploying to Chrome Web Store is unfortunately not possible last I checked, but our release process could certainly improve.

Regardless, there aren't any significant differences between 0.3.1 and 0.2.3, and since the release process is a bit involved and we don't have any current issues on Chrome we'll probably just wait until the next release.

**Comment by johan-bjareholt** [comment]
> Regardless, there aren't any significant differences between 0.3.1 and 0.2.3

Not visually no, but under the hood I think 0.3 is when we started using aw-client-js so that has support for queuing events and pre-merge of events I believe so there are some performance and reliability improvements.

**Comment by ErikBjare** [comment]
Ah right. Apparently we've kept track of it in #27, you should have permissions to update it @johan-bjareholt.

**Comment by je-l** [comment]
Closed as duplicate of #27
