### ISSUE TITLE
Include extension install specific string in the bucket name?

### ISSUE THREAD

**Issue by jackmac92** [ActivityWatch/aw-watcher-web#51]
I have the watcher installed in multiple chrome profiles, what do you think about generating a uuid on extension install, and using that as a suffix [here](https://github.com/ActivityWatch/aw-watcher-web/blob/4e7846c591bf7c604789467648e90e1e9cc7881c/src/client.js#L54) in `getBucketId`?

I can send a PR if you'd consider those changes

**Comment by johan-bjareholt** [comment]
There's little point in having it in different profiles if each profile is identified by a UUID, then it will be very hard to figure out which one is which anyway so I don't think the user gains much from it unless he/she looks that up and remember some part of the UUID (which I think is unlikely).

**Comment by ErikBjare** [comment]
It's not enough to just create another Chrome bucket since we'll have no way of knowing *which* profile is the active one. Your activity would be logged, but it would be very hard (we won't do it) to combine it with data from the window watcher. 

We currently just check that the the window is a Chrome window and then pick the (only) Chrome bucket, if one is available. Having multiple buckets would need that we know which of the buckets to choose, which is much harder (likely involving guesswork around similarities between window and tab titles).

**Comment by jackmac92** [comment]
Yea makes sense re: not putting that info in the bucket name, but I'd still like to store that info somewhere. What about adding it as a field in data? https://github.com/ActivityWatch/aw-watcher-web/blob/master/src/eventPage.js#L47

**Comment by ErikBjare** [comment]
That would log it with every event, which takes a lot of space for
something most users don't care about.

But it would work, so if you really want it you can fork and build the
extension yourself :)

**Comment by johan-bjareholt** [comment]
I'll close this issue, feel free to open it again if you have any questions

**Comment by daroczig** [comment]
Unfortunately, this doesn't seem to be possible with the current Chrome API features? :disappointed: 

* https://stackoverflow.com/questions/28721668/chrome-extension-get-current-profiles-persons-username
* https://bugs.chromium.org/p/chromium/issues/detail?id=504815

**Comment by daroczig** [comment]
Well, not the same, but at least this might work for this purpose to differentiate between chrome windows running with different profiles: https://developer.chrome.com/extensions/identity
