### ISSUE TITLE
Bug report: 'Restore defaults' under 'Categorization'

### ISSUE THREAD

**Issue by Mechular** [ActivityWatch/aw-watcher-web#52]
URL: http://localhost:5600/#/settings

Description: 'Restore defaults' button under 'Categorization' can be clicked without making any changes, resulting in a 'You have unsaved changes!' bootstrap alert message and the option to 'Save' or 'Discard'.

Reason: Uncertainty surrounding 'You have unsaved changes!', 'Save', and 'Discard' as they are not relevant.

Suggested resolution: Hide 'Restore defaults' until a change is made.

![Capture](https://user-images.githubusercontent.com/18108148/82376160-17e45300-99f8-11ea-8427-d42c6ceb4948.PNG)

**Comment by ErikBjare** [comment]
Wrong repo and this isn't really a bug, seems more like a nitpick to me. 

Unlikely we'll bother changing this behavior, so I'm closing.

**Comment by Mechular** [comment]
I clicked report bug and this is where it brought me. You have functionality that is both confusing and illogical. Calling it a nitpick is a good way to deter future support from your client base.

**Comment by ErikBjare** [comment]
Hey, first off, sorry if I offended you. I wrote the reply quickly as I was in a hurry and didn't think much of it. I could have been more considerate. I apologize.

>I clicked report bug and this is where it brought me.

I assume you clicked the link in the web watcher that says "If you find any bugs with this watcher, please report them here"? I can see how that might be confusing, maybe we should word that differently, or simply point people to the main repo (as opposed to this repo for just the web watcher) where we accept bug reports for all of ActivityWatch.

>You have functionality that is both confusing and illogical.

If the user hasn't made any changes then why would they click it? The "unsaved changes" alert acts as a final confirmation to let the user review the defaults before they commit to the restore.

We could check for the case where the user is already using the defaults, but doing such a check would actually complicate the code significantly, and since it makes no sense for them to click it if they are already using the defaults I don't see any significant benefit to fixing it.

>Calling it a nitpick is a good way to deter future support from your client base.

Again, sorry if that came out wrong, I definitely could have worded it differently. I do appreciate your effort, but this minor thing just isn't worth the effort it would take to fix it.

And just to make it clear: There's no client base, we're a community building this for free for the benefit of all. But of course, we don't want to deter potential contributors or users.
