### ISSUE TITLE
Not Collecting Data from Microsoft Edge

### ISSUE THREAD

**Issue by TaylorJonesTRT** [ActivityWatch/aw-watcher-web#61]
I just recently installed ActivityWatch with the chrome browser extension as well. 

AW is detecting that I am using Microsoft Edge which can be seen in the picture below but as well you can see it is not collecting any browser data at all. I was on Twitch for around 7 minutes just to test it out and then on github making sure I couldn't find another issue about this already reported. 

<img width="1136" alt="Screen Shot 2020-11-28 at 9 21 32 AM" src="https://user-images.githubusercontent.com/9523996/100519110-7c2c6000-315b-11eb-84b4-6320303c5607.png">

**Comment by johan-bjareholt** [comment]
Assuming that there is data in the aw-watcher-web-edge bucket I think the issue is because the appnames is "Microsoft Edge" while others have reported it to be just "msedge.exe". We need to add that appname to a list in the web-ui as well for the analysis to know when the edge window is focused and for the summary to be correct.

**Comment by ErikBjare** [comment]
Fixed, it should be working in the next release.
