### ISSUE TITLE
aw-watcher-web-firefox reports hostname as unknown, while other watchers have correct hostname of machine

### ISSUE THREAD

**Issue by phandox** [ActivityWatch/aw-watcher-web#67]
Hi, 

I've installed Firefox extension for aw-watcher and noticed that I don't see any data from Browser in Activity page of UI.
When I've looked at the Raw Data, I can see that the aw-watcher-web-firefox is updated regularly and has all the data, but it reports that the host is unknown, thus not counting this activity in activity view.

I've installed Activity watcher and extension yesterday with most recent versions:
AW version: v0.10.0
Extension version: 0.4.3
OS: Linux, Fedora 33

Can you help me how to get the extension to correctly recognize the hostname?
Thank you.

**Comment by johan-bjareholt** [comment]
This is a known issue, we have a workaround for the web watcher that makes it get handled properly in the web-ui because web extensions are not allowed to know the hostname. So that the hostname is unknown is a known but should not be an issue.

I'll assume that there's something else not working rather than the browser watcher then. One thing to check would be since you are running Fedora would be to check if you are using wayland or not. ActivityWatch does not support wayland yet because there's no API for us to get the window name and application names. The window and afk watchers need to work for the web watcher to work too because otherwise there's no way to know if the user is afk or not or if some other window than the browser is focused.

**Comment by phandox** [comment]
I see, so the Wayland was the issue. I switched to Xorg and now I can see domains and windows in the Activity overview. Thanks for help! Looking forward to Wayland support :)

**Comment by dennys** [comment]
@johan-bjareholt Hi, can you share the workaround for the web watcher to get the hostname? Because I try to export/import web watcher's data from one computer to another, and the buckerid is duplicated.

**Comment by edobez** [comment]
I have the same problem on Vivaldi (using Chrome extension) on Windows.
Data is collected under "unknown" hostname and I can see that the bucket name misses the host name as suffix.
